In [1]:
from IPython.display import display

In [2]:
import pandas as pd

In [3]:

table = pd.read_excel("Market_Status_Info_Report_2025-01-23.xlsx")
display(table)

,Market,Type,Start Scout,End Scout,Status,7-Day Preview,Revised Preview,Actual Preview,10-Day Final,Revised Final,Actual Final
0,"Knoxville, TN",Metro,2025-01-29,2025-02-03,Scheduled,2025-02-12,2025-02-12,NaN,2025-02-18,2025-02-18,NaN
1,"Provo, UT",Metro,2025-01-26,2025-01-31,Scheduled,2025-02-11,2025-02-11,NaN,2025-02-14,2025-02-14,NaN
2,"Allentown, PA",Metro,2025-01-26,2025-01-31,Scheduled,2025-02-11,2025-02-11,NaN,2025-02-14,2025-02-14,NaN
3,"Omaha, NE",Metro,2025-01-26,2025-01-31,Scheduled,2025-02-11,2025-02-11,NaN,2025-02-14,2025-02-14,NaN
4,"Fort Myers, FL",Metro,2025-01-26,2025-01-31,Scheduled,2025-02-11,2025-02-11,NaN,2025-02-14,2025-02-14,NaN
5,Nevada,State Route,2025-01-25,2025-01-29,Scheduled,2025-02-07,2025-02-07,NaN,NaN,NaN,NaN
6,"Reno, NV",Metro,2025-01-25,2025-01-30,Scheduled,2025-02-10,2025-02-10,NaN,2025-02-13,2025-02-13,NaN
7,"Lancaster, PA",Metro,2025-01-25,2025-01-30,Scheduled,2025-02-10,2025-02-10,NaN,2025-02-13,2025-02-13,NaN
8,"McKinney, TX",Metro,2025-01-24,2025-01-29,Scheduled,2025-02-07,2025-02-07,NaN,2025-02-12,2025-02-12,NaN
9,"Jacksonville, FL",Metro,2025-01-24,2025-02-01,Scheduled,2025-02-11,2025-02-11,NaN,2025-02-14,2025-02-14,NaN
10,"Stockton, CA",Metro,2025-01-23,2025-01-28,Scouting,2025-02-06,2025-02-06,NaN,2025-02-11,2025-02-11,NaN
11,"Corpus Christi, TX",Metro,2025-01-23,2025-01-28,Scouting,2025-02-06,2025-02-06,NaN,2025-02-11,2025-02-11,NaN
12,Virginia,State Route,2025-01-23,2025-01-29,Scouting,2025-02-07,2025-02-07,NaN,NaN,NaN,NaN
13,Oregon,State Route,2025-01-22,2025-01-28,Scouting,2025-02-06,2025-02-06,NaN,NaN,NaN,NaN
14,"Fresno, CA",Metro,2025-01-22,2025-01-27,Scouting,2025-03-12,2025-02-05,NaN,2025-03-17,2025-02-10,NaN
15,"Augusta, GA",Metro,2025-01-22,2025-01-27,Scouting,2025-02-05,2025-02-05,NaN,2025-02-10,2025-02-10,NaN
16,Tennessee,State Route,2025-01-22,2025-01-26,Scouting,2025-02-04,2025-02-04,NaN,NaN,NaN,NaN
17,"Greensboro, NC",Metro,2025-01-22,2025-01-27,Scouting,2025-02-05,2025-02-05,NaN,2025-02-10,2025-02-10,NaN